### ISSUE TITLE
Frecuent crashes casting to Lithium thing

### ISSUE THREAD

**Issue by ayosafacundo** [CyclopsMC/IntegratedDynamics#1509]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Modpack: Stacia 2: Expert.
Crash log first line:
`java.lang.ClassCastException: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube cannot be cast to class org.cyclops.integrateddynamics.core.block.VoxelShapeComponents `

Originally, Stacia 2: Expert used an old Integrated Dynamics version. I personally updated it and tested it to the latest version, crashes keep happening.

#### Steps to reproduce the problem:

Honestly I don't know why that's happening.

#### Expected behaviour:

Integrated dynamics shouldn't crash the game.
____

#### Versions:

- This mod: 1.26.0
- Minecraft: 1.19.2
- Mod loader version: Forge 43.4.6

#### Log file:

https://pastebin.com/HmgbQ7Xy

(it WILL be deleted after the 8th of June, if that happens ask me for the log again)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jack-McKalling** [comment]
I know you mention that you updated to the latest version, but have you also tried to reproduce this in a whole new world? It could be that the first occurrence of the crash maintained corrupted data in your save, that didn't get corrected by just updating the mod version.

If you start the test in an updated world that has never crashed before, it may give a different result. If it does give a different result, then it may not have anything to do with our mod.

**Comment by ayosafacundo** [comment]
> have you also tried to reproduce this in a whole new world?

Not thoroughly. Honestly I don't have much free time, and I'd rather pass my time playing instead of bug hunting for yet another project.

You can close the issue if you want.

**Comment by rubensworks** [comment]
This looks like an issue with the Lithium mod. Could you report it to their issue tracker?
Happy to make changes here if needed, so you can link back here.

**Comment by Lisovq** [comment]
I have a similar crash problems on my server. After reading crash logs I also saw a possible Lithium problem, but setting `mixin.shapes=false` parameter in lithium.properties config file did not solve the problem.
`mixin.shapes=false` - disables shape optimization from Lithium mod.

[crash-report.txt](https://github.com/user-attachments/files/20138319/crash-report.txt)
In short: the crash log is almost similar to the original one provided by the creator of the issue, but in my case the cast cannot happen in the vanilla variant of CubeVoxelShape after disabling Lithium optimization.

Old version in use (1.24.1)

**Comment by Lisovq** [comment]
https://github.com/CyclopsMC/IntegratedDynamics/blob/8e9023f510816f1c7cad4c39b2bd7dd52ce3c52e/src/main/java/org/cyclops/integrateddynamics/block/BlockCable.java#L355
line of problem from crash-log stacktrace

from my crash report, and the fact that it can't cast from the vanilla variant(?), then it looks more like a mod issue.
However, I don't have any knowledge of Java

**Comment by Lisovq** [comment]
I'm not sure about my solution, but the crashes stopped haunting the server after changing the following parameter to false in the `integrateddynamics-common.toml` config file:
```
[machine.cable]
	dynamicShape = true # change to false
```
Stacia 2: Expert modpack also has the Cable Facades mod installed, which could conflict if used (in my case I used it to cover ID interfaces).
