### ISSUE TITLE
Crash on 1.15.2 (startup)

### ISSUE THREAD

**Issue by 3x1at1on** [CyclopsMC/IntegratedDynamics#875]
#### Issue type:

- :bug: Bug

____

#### Short description:

Crash on Forge registration section.

#### Steps to reproduce the problem:

Install Integrated dynamics.

#### Expected behaviour:

To load without a crash

____

#### Versions:

- This mod: 1.1.6
- Minecraft: 1.15.2
- Forge: 31.2.23

#### Log file:

Crash log https://pastebin.com/yzT58SkQ
Relevant section in the full log file https://pastebin.com/5A7ifHGs
Full log https://pastebin.com/Lhch7hmG
Full log after Integrated Dynamics was removed (running normally) https://paste.ofcode.org/wdQ6vqPLjF9JpSBFiDcRRb

**Comment by rubensworks** [comment]
At first sight, this seems to be a Mekanism issue.

**Comment by rubensworks** [comment]
I'm unable to reproduce this problem, even with Mekanism installed on the latest Forge version. Could you try without any other mods installed?

**Comment by 3x1at1on** [comment]
It is very odd indeed. As you kindly suggested Mekanism and Intergrated Dynamics work well together alone. I will try and pin-point the culprit mod here but please be patient with me as I need to check 230 mods for that :)
The only thing I cannot understand is why loading is normal without integrated dynamics... This is the mystery for me.

**Comment by Darkere** [comment]
Can confirm this issue exists. But ~200 mods means I don't have time to track anything down :/

**Comment by 3x1at1on** [comment]
Needless to say that I am a big fan of your mod which makes automation more interesting in minecraft, hence worth the effort on my end to try and solve this problem! 

After experimenting for a while, it is a combination of multiple mods that triggers this behaviour. I managed to get it to error (without a crash log though) to this combination of these mods. If I am to remove any of these mods, the game loads normally...

![Mods](https://user-images.githubusercontent.com/22131752/85902895-fa778580-b7fc-11ea-9a47-c79ef5590843.png)
![Error](https://user-images.githubusercontent.com/22131752/85902733-a10f5680-b7fc-11ea-8ea7-ae9833bc629a.png)
Relevant log section https://pastebin.com/64m5JHWg
Full log https://paste.ofcode.org/CMxmimSBmeZ3ZuhPDNRqZb

I don't think I can be of help any further and terribly sorry for that but hopefully that should give you a good place to look into.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/64m5JHWg">[22:25:41] [Render thread/WARN]: No data fixer registered for entity integratedd - Pastebin.com</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://paste.ofcode.org/CMxmimSBmeZ3ZuhPDNRqZb">Paste ofCode</a></strong></div></blockquote>
#881 looks the same to me...

**Comment by NickGrease** [comment]
I'll add to what 3x1at1on is saying - I don't think it's any particular mod - but the **number** of mods installed.  I can load ~22 mods - any 22 (including InDy+Deps)- and it works fine - add one more mod and I get the `Common_Setup Event error` - remove any mod after that and it works again. #881 definitely has more than 20ish mods installed.

**Comment by 3x1at1on** [comment]
Good point NickGrease...
Started wondering whether this issue has something to do with either of these commits
https://github.com/CyclopsMC/IntegratedDynamics/commit/9b018c427932e9483b5789b4b9d38792b9d8c957
https://github.com/CyclopsMC/IntegratedDynamics/commit/f068eda6a18bec7a456eb9cef992b2d7953aa650

**Comment by rubensworks** [comment]
Thanks for the additional information everyone.
I suspect there are multiple parallel problems at play here (menril tree and ingredient component registration).
Do not hesitate to add additional information, everything helps.
I'll try to look into this asap.

**Comment by NickGrease** [comment]
> Thanks for the additional information everyone.
> I suspect there are multiple parallel problems at play here (menril tree and ingredient component registration).
> Do not hesitate to add additional information, everything helps.
> I'll try to look into this asap.

Is there anything in Minecraft or Forge  (a debug config option, or F3 screen) or some sort of 'debug' type mod - anything that might give more insight to you? I'd be happy to help.

**Comment by rubensworks** [comment]
This may be fixed in release 1.1.9.
Please let me know should this not be the case.

**Comment by 3x1at1on** [comment]
Unfortunately remains to error during the common-setup event phase. Just thinking out of the box here. Could it be something in the Common Capabilities or Cyclops Core that is causing this behaviour rather than Integrated Dynamics itself?

https://pastebin.com/FEq6HyAd with ~26 mods (relevant section in the log)

https://pastebin.com/58jQQqWR with ~220 mods (relevant section in the log)

https://paste.ofcode.org/J6yp9U4CPbGJYycDWxQDDm (Full ~26 mods log)

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/FEq6HyAd">[15:50:26] [modloading-worker-0/ERROR]: Exception caught during firing event: nu - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/58jQQqWR">[15:38:36] [Render thread/ERROR]: Exception caught during firing event: The reci - Pastebin.com</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://paste.ofcode.org/J6yp9U4CPbGJYycDWxQDDm">Paste ofCode</a></strong></div></blockquote>

**Comment by NickGrease** [comment]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9
CyclopsCore-1.15.2-1.7.0
CommonCapabilities-1.15.2-2.5.0

**No other mods installed**

No game breaking issues found - though I haven't gotten to testing machines/recipes yet - just flying around.
Nothing in the logs stuck out to me - but here just in case. 
[debug-ID_Only.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842608/debug-ID_Only.log)
[latest-ID_Only.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842609/latest-ID_Only.log)

**All Mods installed (~90)**
![2020-06-28_12 33 23](https://user-images.githubusercontent.com/854582/85953174-74faef00-b93c-11ea-8152-7ed70a0de3c3.png)
[debug-All_Mods.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842646/debug-All_Mods.log)
[latest-All_Mods.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842647/latest-All_Mods.log)

**Random Mods (40 Total)**
These are the logs of a **_successful_** start-up - adding one more mod causes the common_setup event error. 
[debug-Limit_40.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842707/debug-Limit_40.log)
[latest-Limit_40.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842708/latest-Limit_40.log)

**Random Mods from above + 1 (41 Total)**
These are the logs of a **_failed_** start-up.
[debug-Over_41.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842716/debug-Over_41.log)
[latest-Over_41.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4842717/latest-Over_41.log)

**Comment by rubensworks** [comment]
An even different problem seems to be present now:

```
java.lang.NullPointerException
    at org.cyclops.integrateddynamics.metadata.RegistryExportables.load(RegistryExportables.java:12)
```

This one also still occurs (cause is still unknown):
```
java.lang.NullPointerException: The recipe component of org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers$1@49b8d338 was null, it is probably not initialized yet!
    at java.util.Objects.requireNonNull(Unknown Source)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlerRegistry.register(IngredientComponentHandlerRegistry.java:38)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers.onIngredientComponentsPopulated(IngredientComponentHandlers.java:53)
```

**Comment by rubensworks** [comment]
After some more debugging, I tracked down (and possibly fixed) the problem in CyclopsCore.
I am now unable to produce any crash during startup on my end with 46 other mods.

@NickGrease @3x1at1on Could you try this latest dev build to see if this fixes all problems on your end as well?
https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/cyclopscore/CyclopsCore/1.15.2-1.7.0-1090/

<blockquote><div><strong><a href="https://oss.jfrog.org/artifactory/simple/libs-release/org/cyclops/cyclopscore/CyclopsCore/1.15.2-1.7.0-1090/">Index of libs-release/org/cyclops/cyclopscore/CyclopsCore/1.15.2-1.7.0-1090</a></strong></div></blockquote>

**Comment by 3x1at1on** [comment]
I confirm this fixes with the combination of mods I had before ~24 mods
```
java.lang.NullPointerException
    at org.cyclops.integrateddynamics.metadata.RegistryExportables.load(RegistryExportables.java:12)
```

However this remains to persist
```
java.lang.NullPointerException: The recipe component of org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers$1@49b8d338 was null, it is probably not initialized yet!
    at java.util.Objects.requireNonNull(Unknown Source)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlerRegistry.register(IngredientComponentHandlerRegistry.java:38)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers.onIngredientComponentsPopulated(IngredientComponentHandlers.java:53)
```

Relevant log section https://pastebin.com/jN8YEfSK This is with 230~ mods.
This log mentions `org.cyclops.integrateddynamics.IntegratedDynamicsSoundEvents` as the potential culprit for the registration event error. I will dig deeper and reply back here just give me a couple of hours to do so.

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/jN8YEfSK">[16:34:47] [Render thread/ERROR]: Exception caught during firing event: The reci - Pastebin.com</a></strong></div></blockquote>

**Comment by NickGrease** [comment]
MC: 1.15.2
Forge: 31.2.27
IntegratedDynamics-1.15.2-1.1.9
CyclopsCore-1.15.2-1.7.0-1090
CommonCapabilities-1.15.2-2.5.0

Just a heads up - I'm testing now but at the very least I'm able to start the game with 96 mods - started a new world and in the process of looking around - will post logs asap.

Edit:
So this run was with all my mods + TerraForge Beta 2 (I mention TerraForge because there are a few errors in the logs that I think relate to it - and I never was able to find the Meneglin Biome.)

[debug.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4853348/debug.log)
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4853351/latest.log)

Didn't see anything major in the logs - JEI had a few complaints - duplicate recipe or something like that. 

Going to do a default world type - test out world gen and machines / recipes.

Ok, tested default world - wild trees spawning, biome spawning works, everything appears to be in JEI - tested a few machines (nothing complex) - seems good.

**Note** The drops from cutting down trees seems a bit excessive 30+ berries + 10 saplings + 10 crystals from 2 trees. I feel like this might be done on purpose - the assumption being that a person would likely find a 'wild' tree before they find a Meneglin biome - in which case you want to make sure they get sufficient drops in order to begin using the mod. In practice I've found that the 'wild' trees are extremely rare (I like that) and 'accidentally' finding the Meneglin biome *first* seems to happen more often then not - meaning the excessive drops seem... excessive... when your standing in the middle of 100 Meneglin tree biome.

**Comment by 3x1at1on** [comment]
I managed to find the culprit mod! It was Corail Recycler. The minute I removed it, the game loaded successfully and that registery error of integrated dynamics is not there anymore!
```
java.lang.NullPointerException: The recipe component of org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers$1@49b8d338 was null, it is probably not initialized yet!
    at java.util.Objects.requireNonNull(Unknown Source)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlerRegistry.register(IngredientComponentHandlerRegistry.java:38)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers.onIngredientComponentsPopulated(IngredientComponentHandlers.java:53)
```

I am closing this issue as I feel it is completely resolved. Thank you all very much for the effort and help.
Now serious automation beings!

**Comment by NickGrease** [comment]
I would keep it open until the actual fix is pushed to Curse and keep it open a little while after that - people never check closed issues LOL.

**Comment by 3x1at1on** [comment]
Spoke too soon... The other bug is again not related to a certain mod. It happens when you have 190+ mods installed. The minute I drop below 190 then the game load normally.

```
java.lang.NullPointerException: The recipe component of org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers$1@49b8d338 was null, it is probably not initialized yet!
    at java.util.Objects.requireNonNull(Unknown Source)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlerRegistry.register(IngredientComponentHandlerRegistry.java:38)
    at org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers.onIngredientComponentsPopulated(IngredientComponentHandlers.java:53)
```

**Comment by rubensworks** [comment]
Thanks for checking!

> The drops from cutting down trees seems a bit excessive 30+ berries + 10 saplings + 10 crystals from 2 trees.

@NickGrease Could you open an issue for this?

> The other bug is again not related to a certain mod.

@3x1at1on Could you share a zip of all the mods that cause the crash?

**Comment by 3x1at1on** [comment]
Mods folder: https://drive.google.com/file/d/1V8j4X5HpA4Pr9W3_Lf27G2sLhRz5FSjD/view?usp=sharing

Config folder (for good measures): https://drive.google.com/file/d/1n43ufE92-P7Gf_UCn_rrFdbyAlaWpFKl/view?usp=sharing

<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1V8j4X5HpA4Pr9W3_Lf27G2sLhRz5FSjD/view?usp=sharing&usp=embed_facebook">mods.zip</a></strong></div></blockquote>
<blockquote><img src="https://ssl.gstatic.com/docs/doclist/images/icon_14_generic_favicon.ico" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://drive.google.com/file/d/1n43ufE92-P7Gf_UCn_rrFdbyAlaWpFKl/view?usp=sharing&usp=embed_facebook">config.zip</a></strong></div></blockquote>

**Comment by LlubNek** [comment]
not fixed...
minecraft 1.15.2
forge-31.2.29
CyclopsCore-1.15.2-1.7.1.jar
IntegratedDynamics-1.15.2-1.1.10.jar
[crash-2020-07-01_19.36.34-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4861286/crash-2020-07-01_19.36.34-client.txt)
[latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4861288/latest.log)

**Comment by 3x1at1on** [comment]
> not fixed...
> minecraft 1.15.2
> forge-31.2.29
> CyclopsCore-1.15.2-1.7.1.jar
> IntegratedDynamics-1.15.2-1.1.10.jar
> [crash-2020-07-01_19.36.34-client.txt](https://github.com/CyclopsMC/IntegratedDynamics/files/4861286/crash-2020-07-01_19.36.34-client.txt)
> [latest.log](https://github.com/CyclopsMC/IntegratedDynamics/files/4861288/latest.log)

Your log is the same as mine.

I am wondering now if there is something in Common Capabilities causing this, when Integrated Dynamics and Cyclops Core were fixed.

**Comment by rubensworks** [comment]
Fixed in Common Capabilities 2.5.1.
